name: Auto Follow Management

on:
  workflow_dispatch:  # 手動実行トリガー
  schedule:
    - cron: '0 9 * * *'  # 毎日09:00 UTCに実行

jobs:
  manage-follows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run follow sync script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/main.py
