name: Auto Follow Management

on:
  workflow_dispatch:  # 手動実行トリガー
  schedule:
    - cron: '0 22 * * *'  # UTC 22:00は日本時間 7:00

jobs:
  manage-follows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Run follow sync script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python -m scripts.main
